<?xml version="1.0" encoding="UTF-8"?>

<project name="ProductManagement" default="default" basedir=".">
    <description>Builds, tests, and runs the project ProductManagement.</description>
    <import file="nbproject/build-impl.xml"/>
    <property name="src.dir" value="src"/>
    <property name="build.dir" value="build"/>
    <property name="dist.dir" value="dist"/>

    <!-- Dọn dẹp thư mục build -->
    <target name="clean">
        <delete dir="${build.dir}"/>
        <delete dir="${dist.dir}"/>
    </target>

    <!-- Tạo thư mục build nếu chưa có -->
    <target name="init" depends="clean">
        <mkdir dir="${build.dir}"/>
        <mkdir dir="${dist.dir}"/>
    </target>

    <!-- Compile mã nguồn -->
    <target name="compile" depends="init">
        <javac srcdir="${src.dir}" destdir="${build.dir}"/>
    </target>

    <!-- Đóng gói thành file JAR -->
    <target name="build" depends="compile">
        <jar destfile="${dist.dir}/ProductManagement.jar" basedir="${build.dir}">
            <manifest>
                <attribute name="Main-Class" value="Product"/>
            </manifest>
        </jar>
    </target>
</project>
